### ISSUE TITLE
NormalizedPointofInterest2D are actually not normalized (?)

### ISSUE THREAD

**Issue by Luca-Pozzi** [ros4hri/hri_face_detect#4]
Hi!

I am currently using this awesome package to try to implement a video-based diarization of speakers. To do so, I accessed the facial landmarks. Surprisingly, I got them in the typical range of image pixels, though they are represented as a list of `NormalizedPointOfInterest2D`.

Indeed, inspecting the `FaceDetector` in the `detect` script (lines 570 to 691), it looks like facial landmarks are published as non-normalized integers. Below is a subset of those lines, for the sake of readability.

```python
def make_facial_landmarks_msg(self, detection, img_height, img_width):

        # PoI = Points of Interest
        poi = [
            NormalizedPointOfInterest2D(
                int(detection.landmark[ros4hri_to_mediapipe[idx]].x * img_width),
                int(detection.landmark[ros4hri_to_mediapipe[idx]].y * img_height),
                1,
            )
            for idx in range(68)
        ]

```

and below are the values that I get when looking into a `/humans/faces/<face_id>/landmarks`, again cropped for conciseness

```
header: 
  seq: 15
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
landmarks: 
  - 
    x: 274.0
    y: 332.0
    c: 1.0
  - 
    x: 274.0
    y: 345.0
    c: 1.0
  - 
    x: 276.0
    y: 359.0
    c: 1.0
  - 
    x: 278.0
    y: 373.0
    c: 1.0
  - 
    x: 281.0
    y: 386.0
    c: 1.0

    ...
```

Is this the intended behavior? Or should the landmarks be published in the [0.0 1.0] range?

Thank you in advance!
I will be happy to contribute with a PR on this if you confirm me that this has to change.
